const express = require("express")
const cors = require("cors")
const InsertImage  = require("./Image/insertimage")
const GetImage  = require("./Image/getImage")
const upload = require("./multer/multer")
const UnlinkImage  = require("./Image/deleteImage")
const multer = require("multer")
const port = 8080 | process.env.PORT
const app = express()
app.use(cors())
app.use(function (req,res,next) {
    console.log(req.url)
    console.log(req.method)
    next()
})
app.post("/file", upload,function (req,res) {
    console.log(req.files)
    return res.json({message : "Image added successfully", filenames : [...req.files.map(file => file.filename)]})
})
app.get("/get/image/:name",GetImage)
app.post("/",upload,InsertImage)
app.delete("/delete/image/:name",UnlinkImage)
app.listen(port,function () { console.log(`Server listen on port ${port}`)})
