const express = require("express")
const cors = require("cors")
const InsertImage  = require("./Image/insertimage")
const GetImage  = require("./Image/getImage")
const { presentation_image } = require("./multer/multer")
const UnlinkImage  = require("./Image/deleteImage")
const port = 8080
const app = express()
app.use(cors())
app.use(function (req,res,next) {
    next()
})
app.get("/get/image/:name",GetImage)
app.post("/",presentation_image,InsertImage)
app.delete("/delete/image/:name",UnlinkImage)
app.listen(port,function () { console.log(`Server listen on port ${port}`)})